# This workflow will install Python dependencies and run the job analyzer

name: Job Analyzer Service

on:
  # 定时任务：每天北京时间上午11点（UTC 3点）运行
  schedule:
    - cron: '0 3 * * *'
  
  # 允许手动触发（用于测试）
  workflow_dispatch:
  
  # 推送到main分支时也运行（用于测试）
  push:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'  # 缓存pip依赖，加速构建
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 下载spacy模型（根据你的需要调整语言模型）
        python -m spacy download de_core_news_sm
    
    - name: Run job analyzer
      env:
        # 在仓库Settings -> Secrets中配置这些环境变量
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        # 如果有其他配置，也在这里添加
        TZ: 'Asia/Shanghai'  # 设置时区
      run: |
        python analyzer.py
